-- Your SQL goes here
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  share_photos BOOLEAN NOT NULL DEFAULT 'f'
  darkmode BOOLEAN NOT NULL DEFAULT 'f'
);